# Generated by Django 3.2 on 2021-06-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additionalservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('explain', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='additionalservicesimage/')),
            ],
        ),
        migrations.CreateModel(
            name='backgroundimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default='test', null=True, upload_to='bgimage/')),
                ('logo', models.ImageField(blank=True, default='test', null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introtext', models.CharField(max_length=100)),
                ('subtext', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='main_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('redirect', models.CharField(max_length=10)),
                ('explain', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='mainservicesimage/')),
            ],
        ),
        migrations.CreateModel(
            name='Technologylevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.TextField()),
            ],
        ),
    ]
