# Generated by Django 3.2 on 2021-06-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=30)),
                ('photo', models.ImageField(height_field=600, upload_to='Items', width_field=800)),
            ],
        ),
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('image1', models.ImageField(height_field=600, upload_to='setImages', width_field=800)),
                ('price1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='singleimages')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
    ]
